export const data = [
    {
        id: "1",
        image: require("../assets/img/post-photo-01.jpg"),
        title: "Ліс",
        comments: 3,
        likes: 153,
        region: "Ivano-Frankivs'k Region",
        location: "Ukraine",
        latitude: 48.9215,
        longitude: 24.70972,
    },
    {
        id: "2",
        image: require("../assets/img/post-photo-02.jpg"),
        title: "Захід на Чорному морі",
        comments: 0,
        likes: 0,
        region: "Odessa region",
        location: "Ukraine",
        latitude: 46.4461205,
        longitude: 30.771806,
    },
    {
        id: "3",
        image: require("../assets/img/post-photo-03.jpg"),
        title: "Старий будиночок у Венеції",
        comments: 50,
        likes: 200,
        region: "Venezia",
        location: "Italy",
        latitude: 45.438759,
        longitude: 12.327145,
    },
];
